### ISSUE TITLE
compilation error [lammps_src = lammps-23Jun2022]

### ISSUE THREAD

**Issue by pinkutech** [sekocha/lammps-mlip-package#4]
The earlier version was easy to compile, but the new version shows multiple errors. 

../pair_polymlp.cpp: In member function ‘void LAMMPS_NS::PairPolyMLP::read_pot(char*)’:
../pair_polymlp.cpp:904:37: error: no matching function for call to ‘LAMMPS_NS::PairPolyMLP::get_value<int>(std::ifstream&, std::string&)’
  904 |         int version = get_value<int>(input, tag);
      |                       ~~~~~~~~~~~~~~^~~~~~~~~~~~
../pair_polymlp_noforce.cpp: In member function ‘void LAMMPS_NS::PairPolyMLPNoForce::read_pot(char*)’:
../pair_polymlp_noforce.cpp:802:69: error: no matching function for call to ‘Readgtinv::Readgtinv(int&, vector1i&, std::vector<bool>&, std::vector<std::__cxx11::basic_string<char> >::size_type)’
  802 |         Readgtinv rgt(gtinv_order, gtinv_maxl, gtinv_sym, ele.size());
      |                                                                     ^
In file included from ../pair_polymlp_noforce.h:38,
                 from ../pair_polymlp_noforce.cpp:42:
../polymlp_read_gtinv.h:30:5: note: candidate: ‘Readgtinv::Readgtinv(const int&, const vector1i&, const std::vector<bool>&, const int&, const int&)’
   30 |     Readgtinv(const int& gtinv_order,
      |     ^~~~~~~~~
In file included from ../pair_polymlp.cpp:34:
../pair_polymlp.h:113:26: note: candidate: ‘T LAMMPS_NS::PairPolyMLP::get_value(std::ifstream&) [with T = int; std::ifstream = std::basic_ifstream<char>]’
  113 |   template<typename T> T get_value(std::ifstream& input);
      |                          ^~~~~~~~~
../polymlp_read_gtinv.h:30:5: note:   candidate expects 5 arguments, 4 provided
../pair_polymlp.h:113:26: note:   candidate expects 1 argument, 2 provided
../polymlp_read_gtinv.h:29:5: note: candidate: ‘Readgtinv::Readgtinv()’
   29 |     Readgtinv();
      |     ^~~~~~~~~
../polymlp_read_gtinv.h:29:5: note:   candidate expects 0 arguments, 4 provided
../polymlp_read_gtinv.h:15:7: note: candidate: ‘Readgtinv::Readgtinv(const Readgtinv&)’
   15 | class Readgtinv {
      |       ^~~~~~~~~
../polymlp_read_gtinv.h:15:7: note:   candidate expects 1 argument, 4 provided
../pair_polymlp.cpp: At global scope:
../pair_polymlp.cpp:950:3: error: no declaration matches ‘T LAMMPS_NS::PairPolyMLP::get_value(std::ifstream&, std::string&)’
  950 | T PairPolyMLP::get_value(std::ifstream& input, std::string& tag){
      |   ^~~~~~~~~~~
In file included from ../pair_polymlp.cpp:34:
../pair_polymlp.h:113:26: note: candidate is: ‘template<class T> T LAMMPS_NS::PairPolyMLP::get_value(std::ifstream&)’
  113 |   template<typename T> T get_value(std::ifstream& input);
      |                          ^~~~~~~~~
../pair_polymlp.h:47:7: note: ‘class LAMMPS_NS::PairPolyMLP’ defined here
   47 | class PairPolyMLP : public Pair {
      |       ^~~~~~~~~~~
make[1]: *** [Makefile:114: pair_polymlp_noforce.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:114: pair_polymlp.o] Error 1
make[1]: Leaving directory '/opt/lammps-23Jun2022/src/Obj_serial'
make: *** [Makefile:394: serial] Error 2

**Comment by sekocha** [comment]
I reproduced these compilation errors and fixed the corresponding part. The latest version can now be compiled.
